version: '3'

services:
  mariadb:
    image: mariadb
    restart: always
    env_file:
      - mariadb/mariadb.conf
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/1_init.sql
      - ./mariadb/insert.sql:/docker-entrypoint-initdb.d/2_insert.sql

  auth:
    image: auth-api:latest
    build:
      context: ./auth-api
    ports:
      - "8000:8000"
    depends_on:
      - mariadb
    environment:
      - SQLALCHEMY_DATABASE_URL=mariadb+mariadbconnector://denstrygin:4054@mariadb:3306/messenger

  groupchat:
    image: groupchat-api:latest
    build:
      context: ./groupchat-api
    ports:
      - "8001:8001"
    depends_on:
      - mariadb
    environment:
      - SQLALCHEMY_DATABASE_URL=mariadb+mariadbconnector://denstrygin:4054@mariadb:3306/messenger

  ptp:
    image: ptp-api:latest
    build:
      context: ./ptp-api
    ports:
      - "8002:8002"
    depends_on:
      - mariadb
    environment:
      - SQLALCHEMY_DATABASE_URL=mariadb+mariadbconnector://denstrygin:4054@mariadb:3306/messenger

volumes:
  mariadb_data:
    driver: local